spring:
  application:
    name: 31-Microservices-WelcomeAPI
  boot:
    admin:
      client:
        url: http://localhost:1111
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always